name: carsharing

services:
  postgres:
    image: postgres:16
    container_name: carsharing-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: carsharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - carsharing_postgres_data:/var/lib/postgresql/data

volumes:
  carsharing_postgres_data: